language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t grohankarn/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true grohankarn/docker-react npm run test